name: Reftest

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: "Path of reftest config"
        required: false
        default: "reftest.config.json"
  schedule:
    # 平日9時15分(JST)に実行
    - cron: "15 0 * * 1-5"

env:
  BUILD_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  RESULT_URL: "https://akashic-contents.github.io/website-contents/reftest-output"
  OUTPUT_HTML_DIR: "/tmp/reftest-output-tmp"
  ERROR_SCREENSHOTS_DIR: "/tmp/error-screenshots"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  reftest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Setup locale for Japanese
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-ja fonts-noto-cjk
          sudo locale-gen ja_JP.UTF-8

      - name: Build contents
        run: npm ci

      - name: Run reftest
        run: |
          # engine-files-reftest実行時になぜかchromedriverのインストールが行われてしまうため--chromedriver-skip-installオプションを追加
          npx --chromedriver-skip-install @akashic/engine-files-reftest@latest -- --output-html "${OUTPUT_HTML_DIR}" --configure "${CONFIG_PATH}" --timeout-error-dir-path "${ERROR_SCREENSHOTS_DIR}" --error-screenshot-dir-path "${ERROR_SCREENSHOTS_DIR}"
        env:
          CONFIG_PATH: ${{ inputs.config_path || 'reftest.config.json' }}

      - name: Upload result
        if: always()
        run: |
          git checkout .
          git checkout gh-pages
          rm -rf reftest-output/*
          cp -rp ${OUTPUT_HTML_DIR}/* reftest-output/
          git add reftest-output
          if [[ -n "$(git diff --cached --shortstat)" ]]; then
            git config user.name 'github-actions'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "Save Reftest Output (Build Url: ${BUILD_URL} )"
            git push origin gh-pages
          fi

      # エラー時のスクリーンショット画像をアップロード
      - name: Upload error screenshots
        if: failure()
        id: upload_error_screenshots
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: error-screenshots
          path: ${{ env.ERROR_SCREENSHOTS_DIR }}
          if-no-files-found: ignore

      #-- Slack通知 --#
      # 成功
      - name: Notify Slack on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"attachments": [{"color": "#00ff00","pretext": "Reftest Result('"${GITHUB_REPOSITORY}"'): '"${RESULT_URL}"'", "fields":[{"title":"SUCCEED","value":"BUILD: '"${BUILD_URL}"'","short":false}]}]}' ${SLACK_WEBHOOK_URL}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_GYOMUKAIZEN }}

      # 失敗
      - name: Notify Slack on failure with artifact link
        if: failure()
        run: |
          ARTIFACT_URL=""
          if [ -n "${STEPS_UPLOAD_ERROR_SCREENSHOTS_OUTPUTS_ARTIFACT_ID}" ]; then
            ARTIFACT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${STEPS_UPLOAD_ERROR_SCREENSHOTS_OUTPUTS_ARTIFACT_ID}"
          fi
          curl -X POST -H 'Content-type: application/json' --data '{"attachments": [{"color": "#ff0000","pretext": "Reftest Result('"${GITHUB_REPOSITORY}"'): '"${RESULT_URL}"'", "fields":[{"title":"FAILED","value":"BUILD: '"${BUILD_URL}"'\nError Screenshots: '"${ARTIFACT_URL}"'","short":false}]}]}' ${SLACK_WEBHOOK_URL}
        env:
          STEPS_UPLOAD_ERROR_SCREENSHOTS_OUTPUTS_ARTIFACT_ID: ${{ steps.upload_error_screenshots.outputs.artifact-id }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_GYOMUKAIZEN }}
