name: Update Reftest Expected Images

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: "Path of reftest config"
        required: false
        default: "reftest.config.json"
      update_only_diff:
        description: "Update only if there are differences in content, scenario, or test settings"
        required: false
        type: boolean
        default: false

env:
  BUILD_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  ERROR_SCREENSHOTS_DIR: "/tmp/error-screenshots"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  reftest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Setup locale for Japanese
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-ja fonts-noto-cjk
          sudo locale-gen ja_JP.UTF-8

      - name: Build contents
        run: npm ci

      - name: Run reftest
        run: |
          # engine-files-reftest実行時になぜかchromedriverのインストールが行われてしまうため--chromedriver-skip-installオプションを追加
          CMD="npx --chromedriver-skip-install @akashic/engine-files-reftest@latest -- --configure ${CONFIG_PATH} --timeout-error-dir-path ${{ env.ERROR_SCREENSHOTS_DIR }} --error-screenshot-dir-path ${{ env.ERROR_SCREENSHOTS_DIR }}"
          if [[ "${{ inputs.update_only_diff }}" == "true" ]]; then
            CMD="$CMD --update-diff"
          else
            CMD="$CMD --update"
          fi
          eval $CMD
        env:
          CONFIG_PATH: ${{ inputs.config_path || 'reftest.config.json' }}

      - name: Update Expected Images
        run: |
          BASE_BRANCH=${GITHUB_REF#refs/heads/}
          TARGET_BRANCH=github-actions/update-expected-images-$(date +'%Y%m%d-%H%M%S')
          git checkout $TARGET_BRANCH 2>/dev/null || git checkout -b $TARGET_BRANCH
          git add */expected/*
          if [[ -n "$(git diff --cached --shortstat)" ]]; then
            git config user.name 'github-actions'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "Update Expected Images (Build Url: ${BUILD_URL} )"
            git push origin $TARGET_BRANCH -f
            gh pr create \
              --title "Update reftest expected images" \
              --body "This PR updates the reftest expected images." \
              --base $BASE_BRANCH \
              --head $TARGET_BRANCH
          else
            echo "正解画像更新の必要がなかったためスキップ"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # エラー時のスクリーンショット画像をアップロード
      - name: Upload error screenshots
        if: failure()
        id: upload_error_screenshots
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: error-screenshots
          path: ${{ env.ERROR_SCREENSHOTS_DIR }}
          if-no-files-found: ignore
